CREATE TABLE Comprobantes (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Tipo INT NOT NULL,
    RucEmisor NVARCHAR(11) NOT NULL,
    RazonSocialEmisor NVARCHAR(100) NOT NULL,
    Monto DECIMAL(18,2) NOT NULL,
    FechaEmision DATETIME2 NOT NULL
);
